# Generated by Django 4.1.7 on 2023-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='duration_in_mills',
            field=models.IntegerField(default=0),
        ),
    ]
