# Generated by Django 4.1.3 on 2022-11-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_respondent_created_at_respondent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respondent',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
