# Generated by Django 4.1.3 on 2022-12-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_respondent_age_alter_respondent_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Respondent',
            new_name='Participant',
        ),
        migrations.AlterModelTable(
            name='participant',
            table='participants',
        ),
    ]
