# Generated by Django 4.1.7 on 2023-03-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_created_by_user_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audios_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='audios_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='audios_rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='audios_submitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='audios_validated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='estimated_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
