# Generated by Django 4.1.3 on 2022-12-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_respondent_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='local_id',
            field=models.IntegerField(default=0),
        ),
    ]
