# Generated by Django 4.1.7 on 2023-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_audios_accepted_user_audios_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_ids',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
