# Generated by Django 4.1.3 on 2023-01-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_activitylog_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
