# Generated by Django 4.1.7 on 2023-04-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reference_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='restricted_audio_count',
            field=models.IntegerField(default=10),
        ),
    ]
