# Generated by Django 4.1.3 on 2023-01-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_image_batch',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
