# Generated by Django 4.1.7 on 2023-04-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_reference_code_user_restricted_audio_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conflicts_resolved',
            field=models.IntegerField(default=0),
        ),
    ]
