# Generated by Django 4.1.7 on 2023-04-20 03:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_conflicts_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='recording_benefit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='transcription_benefit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='validation_benefit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
