# Generated by Django 4.1.7 on 2023-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audios_transcribed',
            field=models.IntegerField(default=0),
        ),
    ]
