# Generated by Django 4.1.3 on 2023-01-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_network',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
