# Generated by Django 4.1.3 on 2023-01-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_phone_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_audio_batch',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
