# Generated by Django 4.1.3 on 2023-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
