# Generated by Django 4.1.7 on 2023-05-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_proxy_audios_accepted_in_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proxy_audios_rejected_in_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
