# Generated by Django 4.1.3 on 2023-01-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_accepted_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recording_environment',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
