# Generated by Django 4.1.7 on 2023-05-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_proxy_audios_rejected_in_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transcriptions_resolved',
            field=models.IntegerField(default=0),
        ),
    ]
