# Generated by Django 4.1.7 on 2023-05-25 20:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_transcriptions_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audios_submitted_via_others',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='recording_via_others_benefit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
