# Generated by Django 4.1.7 on 2023-05-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_audios_submitted_via_others_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='audios_submitted_via_others',
            new_name='accepted_audios_submitted_via_others',
        ),
    ]
