# Generated by Django 4.1.3 on 2023-01-23 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupPerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_setup', 'Can manage system setup'), ('validate_image', 'Can validate image'), ('validate_audio', 'Can validate audio'), ('transcribe_audio', 'Can transcribe audio'), ('validate_transcription', 'Can validate transcription'), ('manage_collected_data', 'Can manage collected data'), ('manage_payment', 'Can manage payments'), ('record_self', 'Can record oneself'), ('record_others', 'Can record others')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='demovideo/')),
                ('sms_sender_id', models.CharField(default='LOCALVOICE', max_length=11, unique=True)),
                ('api_key', models.CharField(default='', max_length=50, unique=True)),
                ('send_sms', models.BooleanField(default=True)),
                ('max_background_noise_level', models.IntegerField(default=100)),
                ('max_category_for_image', models.IntegerField(default=5)),
                ('required_image_validation_count', models.IntegerField(default=3)),
                ('required_audio_validation_count', models.IntegerField(default=3)),
                ('required_transcription_validation_count', models.IntegerField(default=3)),
                ('required_image_description_count', models.IntegerField(default=3)),
                ('number_of_batches', models.IntegerField(default=10)),
                ('android_apk', models.FileField(blank=True, null=True, upload_to='apks/')),
                ('amount_per_audio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('participant_privacy_statement', models.TextField(blank=True, default='', null=True)),
                ('enumerators_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_enumerator_group', to='auth.group')),
                ('validators_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_validator_group', to='auth.group')),
            ],
        ),
    ]
