# Generated by Django 3.2.11 on 2022-09-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysconfig',
            name='api_key',
            field=models.CharField(default='OkRvZHppQDE1MDQ=', max_length=50, unique=True),
        ),
    ]
