# Generated by Django 4.1.3 on 2023-02-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_rename_amount_per_audio_appconfiguration_amount_per_audio_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='max_image_for_validation_per_user',
            field=models.IntegerField(default=300),
        ),
    ]
