# Generated by Django 4.1.3 on 2022-12-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_sysconfig_api_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationDocumentType',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.DeleteModel(
            name='RetirementReason',
        ),
        migrations.AlterModelOptions(
            name='setupperms',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_setup', 'Can manage system setup'), ('validate_image', 'Can validate image'), ('validate_audio', 'Can validate audio'), ('transcribe_audio', 'Can transcribe audio'), ('validate_transcription', 'Can validate transcription')]},
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='api_key',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
