# Generated by Django 4.1.7 on 2023-02-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_appconfiguration_max_image_for_validation_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='participant_privacy_statement_audio_akan',
            field=models.FileField(blank=True, null=True, upload_to='privacy_statement_audios'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='participant_privacy_statement_audio_dagaare',
            field=models.FileField(blank=True, null=True, upload_to='privacy_statement_audios'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='participant_privacy_statement_audio_dagbani',
            field=models.FileField(blank=True, null=True, upload_to='privacy_statement_audios'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='participant_privacy_statement_audio_ewe',
            field=models.FileField(blank=True, null=True, upload_to='privacy_statement_audios'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='participant_privacy_statement_audio_ikposo',
            field=models.FileField(blank=True, null=True, upload_to='privacy_statement_audios'),
        ),
    ]
