# Generated by Django 4.1.3 on 2022-12-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_delete_applicationdocumenttype_delete_rank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setupperms',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_setup', 'Can manage system setup'), ('validate_image', 'Can validate image'), ('validate_audio', 'Can validate audio'), ('transcribe_audio', 'Can transcribe audio'), ('validate_transcription', 'Can validate transcription'), ('manage_collected_data', 'Can manage collected data')]},
        ),
    ]
