# Generated by Django 4.1.3 on 2022-12-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_alter_setupperms_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='demovideo/')),
                ('sms_sender_id', models.CharField(default='LOCALVOICE', max_length=11, unique=True)),
                ('api_key', models.CharField(default='', max_length=50, unique=True)),
                ('send_sms', models.BooleanField(default=True)),
                ('max_background_noise_level', models.IntegerField(default=100)),
                ('max_category_for_image', models.IntegerField(default=5)),
            ],
        ),
        migrations.DeleteModel(
            name='SysConfig',
        ),
    ]
