# Generated by Django 4.1.7 on 2023-03-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_appconfiguration_participant_privacy_statement_audio_akan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiguration',
            name='demo_video',
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='demo_video_akan',
            field=models.FileField(blank=True, null=True, upload_to='demovideos'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='demo_video_dagaare',
            field=models.FileField(blank=True, null=True, upload_to='demovideos'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='demo_video_dagbani',
            field=models.FileField(blank=True, null=True, upload_to='demovideos'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='demo_video_ewe',
            field=models.FileField(blank=True, null=True, upload_to='demovideos'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='demo_video_ikposo',
            field=models.FileField(blank=True, null=True, upload_to='demovideos'),
        ),
    ]
