# Generated by Django 4.1.7 on 2023-03-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_remove_appconfiguration_demo_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='allow_recording_more_than_required_per_participant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='allow_saving_less_than_required_per_participant',
            field=models.BooleanField(default=False),
        ),
    ]
