# Generated by Django 4.1.3 on 2022-12-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_appconfiguration_delete_sysconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='required_image_description_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='required_image_validation_count',
            field=models.IntegerField(default=3),
        ),
    ]
