# Generated by Django 4.1.3 on 2022-12-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_appconfiguration_required_image_description_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='required_audio_validation_count',
            field=models.IntegerField(default=3),
        ),
    ]
