# Generated by Django 4.1.3 on 2022-12-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_appconfiguration_required_audio_validation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='required_transcription_validation_count',
            field=models.IntegerField(default=3),
        ),
    ]
