# Generated by Django 4.1.3 on 2023-01-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_appconfiguration_required_transcription_validation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='number_of_batches',
            field=models.IntegerField(default=10),
        ),
    ]
