# Generated by Django 4.1.7 on 2023-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_alter_setupperms_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='hours_to_keep_audios_for_validation',
            field=models.IntegerField(default=6),
        ),
    ]
