# Generated by Django 4.1.3 on 2023-01-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('setup', '0009_appconfiguration_number_of_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='enumerators_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
