# Generated by Django 4.1.7 on 2023-04-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_appconfiguration_hours_to_keep_audios_for_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='hours_to_keep_audios_for_validation',
            field=models.IntegerField(default=12),
        ),
    ]
