# Generated by Django 4.1.3 on 2023-01-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_appconfiguration_enumerators_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='android_apk',
            field=models.FileField(blank=True, null=True, upload_to='apks/'),
        ),
    ]
