# Generated by Django 4.1.7 on 2023-04-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_alter_appconfiguration_hours_to_keep_audios_for_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiguration',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='appconfiguration',
            name='send_sms',
        ),
        migrations.RemoveField(
            model_name='appconfiguration',
            name='sms_sender_id',
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='current_apk_versions',
            field=models.CharField(default='', max_length=11),
        ),
    ]
