# Generated by Django 4.1.3 on 2023-01-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_appconfiguration_android_apk'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='amount_per_audio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
