# Generated by Django 4.1.3 on 2023-01-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_appconfiguration_amount_per_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='participant_privacy_statement',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
