# Generated by Django 4.1.7 on 2023-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('setup', '0013_appconfiguration_default_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='limited_groups',
            field=models.ManyToManyField(related_name='configurations', to='auth.group'),
        ),
    ]
