# Generated by Django 4.1.7 on 2023-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_appconfiguration_limited_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='hours_to_keep_audios_for_transcription',
            field=models.IntegerField(default=12),
        ),
    ]
