# Generated by Django 4.1.3 on 2023-01-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('setup', '0014_alter_setupperms_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='validators_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_validator_group', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='enumerators_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_enumerator_group', to='auth.group'),
        ),
    ]
