# Generated by Django 4.1.3 on 2023-01-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_appconfiguration_validators_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setupperms',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_setup', 'Can manage system setup'), ('validate_image', 'Can validate image'), ('validate_audio', 'Can validate audio'), ('transcribe_audio', 'Can transcribe audio'), ('validate_transcription', 'Can validate transcription'), ('manage_collected_data', 'Can manage collected data'), ('manage_payment', 'Can manage payments'), ('record_self', 'Can record oneself'), ('record_others', 'Can record others')]},
        ),
    ]
