# Generated by Django 4.1.3 on 2022-12-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='demovideo/')),
            ],
        ),
    ]
