# Generated by Django 4.1.3 on 2022-12-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='demovideo/')),
                ('max_background_noise_level', models.IntegerField(default=100)),
                ('max_category_for_image', models.IntegerField(default=5)),
            ],
        ),
        migrations.DeleteModel(
            name='MobileAppConfiguration',
        ),
    ]
