# Generated by Django 4.1.3 on 2022-12-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_appconfiguration_delete_mobileappconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppConfiguration',
        ),
    ]
