# Generated by Django 4.1.7 on 2023-03-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_statistics', '0003_alter_statistics_akan_audios_approved_in_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='akan_audios_approved_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='akan_audios_double_validation_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='akan_audios_single_validation_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='akan_audios_submitted_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='akan_audios_transcribed_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='akan_audios_validation_conflict_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='audios_hours_approved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='audios_hours_submitted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='audios_hours_transcribed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagaare_audios_approved_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagaare_audios_double_validation_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagaare_audios_single_validation_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagaare_audios_submitted_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagaare_audios_transcribed_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagaare_audios_validation_conflict_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagbani_audios_approved_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagbani_audios_double_validation_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagbani_audios_single_validation_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagbani_audios_submitted_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagbani_audios_transcribed_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dagbani_audios_validation_conflict_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ewe_audios_approved_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ewe_audios_double_validation_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ewe_audios_single_validation_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ewe_audios_submitted_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ewe_audios_transcribed_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ewe_audios_validation_conflict_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ikposo_audios_approved_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ikposo_audios_double_validation_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ikposo_audios_single_validation_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ikposo_audios_submitted_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ikposo_audios_transcribed_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ikposo_audios_validation_conflict_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
