# Generated by Django 4.1.7 on 2023-06-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_statistics', '0005_statistics_audios_hours_transcribed_single_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='audios_hours_transcribed_single',
            new_name='akan_audios_transcribed_in_hours_unique',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='audios_transcribed_single',
            new_name='akan_audios_transcribed_unique',
        ),
        migrations.AddField(
            model_name='statistics',
            name='audios_hours_transcribed_unique',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='statistics',
            name='audios_transcribed_unique',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='dagaare_audios_transcribed_in_hours_unique',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='statistics',
            name='dagaare_audios_transcribed_unique',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='dagbani_audios_transcribed_in_hours_unique',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='statistics',
            name='dagbani_audios_transcribed_unique',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='ewe_audios_transcribed_in_hours_unique',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='statistics',
            name='ewe_audios_transcribed_unique',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='ikposo_audios_transcribed_in_hours_unique',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='statistics',
            name='ikposo_audios_transcribed_unique',
            field=models.IntegerField(default=0),
        ),
    ]
