# Generated by Django 4.1.3 on 2023-01-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_wallet_user_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('response_data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='new', max_length=255, null=True)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.wallet')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
