# Generated by Django 4.1.7 on 2023-06-19 01:43

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='accepted_by_provider',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='network',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='new', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(db_index=True, default=payments.models.Transaction.generate_id, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_balances_updated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
