# Generated by Django 4.1.3 on 2023-01-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_initiated_by_transaction_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='directions',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='OUT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_updated',
            field=models.BooleanField(default=False),
        ),
    ]
