# Generated by Django 4.1.3 on 2023-01-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_directions_transaction_wallet_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status_message',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=255, null=True),
        ),
    ]
