# Generated by Django 4.1.3 on 2023-01-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
