# Generated by Django 4.1.3 on 2023-01-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet_updated',
            new_name='wallet_balances_updated',
        ),
        migrations.AddField(
            model_name='transaction',
            name='accepted_by_provider',
            field=models.BooleanField(default=False),
        ),
    ]
