# Generated by Django 4.1.3 on 2023-01-21 15:52

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_wallet_updated_transaction_wallet_balances_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=payments.models.Transaction.generate_id, max_length=20),
        ),
    ]
