# Generated by Django 4.1.3 on 2023-01-21 15:56

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_transaction_status_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=payments.models.Transaction.generate_id, max_length=20, unique=True),
        ),
    ]
