# Generated by Django 4.1.3 on 2023-01-23 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audios/')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_count', models.IntegerField(db_index=True, default=0)),
                ('transcription_count', models.IntegerField(default=0)),
                ('year', models.IntegerField(blank=True, default=2023, null=True)),
                ('locale', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, default=-1, null=True)),
                ('environment', models.CharField(blank=True, max_length=255, null=True)),
                ('is_accepted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audios',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validations',
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(db_index=True, default=False)),
                ('validation_count', models.IntegerField(db_index=True, default=0)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='dashboard.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
                ('validations', models.ManyToManyField(blank=True, related_name='transcription_validations', to='dashboard.validation')),
            ],
            options={
                'db_table': 'transcriptions',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momo_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('network', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('audio_duration_in_seconds', models.IntegerField(default=0)),
                ('paid', models.BooleanField(db_index=True, default=False)),
                ('accepted_privacy_policy', models.BooleanField(default=False)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to='payments.transaction')),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, null=True, unique=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_accepted', models.BooleanField(db_index=True, default=False)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('validation_count', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_number', models.IntegerField(blank=True, db_index=True, default=-1, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='images', to='dashboard.category')),
                ('validations', models.ManyToManyField(blank=True, related_name='image_validations', to='dashboard.validation')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='dashboard.image'),
        ),
        migrations.AddField(
            model_name='audio',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='dashboard.participant'),
        ),
        migrations.AddField(
            model_name='audio',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audio',
            name='validations',
            field=models.ManyToManyField(blank=True, related_name='audio_validations', to='dashboard.validation'),
        ),
    ]
