# Generated by Django 4.1.3 on 2023-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_audio_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='api_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='api_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
