# Generated by Django 4.1.3 on 2022-12-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_category_options_alter_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='images', to='dashboard.category'),
        ),
    ]
