# Generated by Django 4.1.7 on 2023-02-28 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_image_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_images', to='dashboard.category'),
        ),
    ]
