# Generated by Django 4.1.3 on 2022-12-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_image_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
