# Generated by Django 4.1.7 on 2023-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_image_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
