# Generated by Django 4.1.3 on 2022-12-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_image_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
