# Generated by Django 4.1.3 on 2022-12-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_image_image_downloaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_downloaded',
            new_name='is_downloaded',
        ),
    ]
