# Generated by Django 4.1.3 on 2022-12-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_image_downloaded_image_is_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='validation_count',
            field=models.IntegerField(default=0),
        ),
    ]
