# Generated by Django 4.1.7 on 2023-03-16 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_image_deleted_image_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audios', to='dashboard.image'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcriptions', to='dashboard.audio'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
