# Generated by Django 4.1.7 on 2023-03-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_audio_image_alter_audio_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
