# Generated by Django 4.1.7 on 2023-03-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_audio_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
