# Generated by Django 4.1.3 on 2022-12-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_category_name_alter_image_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/'),
        ),
    ]
