# Generated by Django 4.1.7 on 2023-03-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_audio_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
