# Generated by Django 4.1.3 on 2023-01-01 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_audio_alter_image_thumbnail_participant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagevalidation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagevalidation',
            name='user',
        ),
        migrations.DeleteModel(
            name='AudioValidation',
        ),
        migrations.DeleteModel(
            name='ImageValidation',
        ),
        migrations.AddField(
            model_name='audio',
            name='validations',
            field=models.ManyToManyField(related_name='audio_validations', to='dashboard.validation'),
        ),
        migrations.AddField(
            model_name='image',
            name='validations',
            field=models.ManyToManyField(related_name='image_validations', to='dashboard.validation'),
        ),
    ]
