# Generated by Django 4.1.7 on 2023-03-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_transcription_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='type',
            field=models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('ASSISTED', 'ASSISTED')], default='ASSISTED', max_length=100),
        ),
    ]
