# Generated by Django 4.1.3 on 2023-01-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_validation_remove_imagevalidation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='validations',
            field=models.ManyToManyField(blank=True, related_name='audio_validations', to='dashboard.validation'),
        ),
        migrations.AlterField(
            model_name='image',
            name='validations',
            field=models.ManyToManyField(blank=True, related_name='image_validations', to='dashboard.validation'),
        ),
    ]
