# Generated by Django 4.1.7 on 2023-03-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_participant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.CharField(choices=[('INDEPENDENT', 'INDEPENDENT'), ('ASSISTED', 'ASSISTED')], default='ASSISTED', max_length=100),
        ),
    ]
