# Generated by Django 4.1.3 on 2023-01-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_audio_validations_alter_image_validations'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='validation_count',
            field=models.IntegerField(default=0),
        ),
    ]
