# Generated by Django 4.1.7 on 2023-03-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_audio_audio_status_audio_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='file_mp3',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
