# Generated by Django 4.1.3 on 2023-01-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_transcription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='submitted_by',
            new_name='user',
        ),
    ]
