# Generated by Django 4.1.3 on 2023-01-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_submitted_by_transcription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='transcription_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transcription',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
