# Generated by Django 4.1.7 on 2023-04-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_audio_file_mp3'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='flatten',
            field=models.BooleanField(default=False),
        ),
    ]
