# Generated by Django 4.1.7 on 2023-04-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_participant_flatten'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='transcription_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending'), ('conflict', 'conflict')], db_index=True, default='pending', max_length=100),
        ),
    ]
