# Generated by Django 4.1.7 on 2023-04-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_transcription_transcription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='checked_in_for_transcription',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
