# Generated by Django 4.1.3 on 2023-01-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_transaction_participant_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='network',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='new', max_length=255, null=True),
        ),
    ]
