# Generated by Django 4.1.7 on 2023-04-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_audio_checked_in_for_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='transcription_status',
            field=models.TextField(choices=[('in_review', 'in_review'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], db_index=True, default='pending'),
        ),
    ]
