# Generated by Django 4.1.7 on 2023-04-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_audio_transcription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='corrected_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
