# Generated by Django 4.1.3 on 2023-01-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_participant_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='batch_number',
            field=models.ImageField(default=-1, upload_to=''),
        ),
    ]
