# Generated by Django 4.1.7 on 2023-04-11 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_transcription_conflict_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='main_file_format',
            field=models.CharField(default='wav', max_length=5),
        ),
        migrations.AlterField(
            model_name='audio',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audios', to='dashboard.participant'),
        ),
    ]
