# Generated by Django 4.1.3 on 2023-01-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_image_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='batch_number',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
