# Generated by Django 4.1.7 on 2023-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_audio_main_file_format_alter_audio_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='main_file_format',
            field=models.CharField(db_index=True, default='wav', max_length=5),
        ),
    ]
