# Generated by Django 4.1.3 on 2023-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
