# Generated by Django 4.1.7 on 2023-04-14 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0024_alter_audio_main_file_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioValidationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('audios', models.ManyToManyField(related_name='assignments', to='dashboard.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aligned_audios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
