# Generated by Django 4.1.7 on 2023-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_audiovalidationassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovalidationassignment',
            name='audios',
            field=models.ManyToManyField(db_index=True, related_name='assignments', to='dashboard.audio'),
        ),
    ]
