# Generated by Django 4.1.3 on 2023-01-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accepted_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
