# Generated by Django 4.1.3 on 2023-01-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_wallet_user_wallet'),
        ('dashboard', '0026_participant_accepted_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.wallet'),
        ),
    ]
