# Generated by Django 4.1.7 on 2023-04-20 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0026_alter_audiovalidationassignment_audios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to=settings.AUTH_USER_MODEL),
        ),
    ]
