# Generated by Django 4.1.7 on 2023-04-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_validation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
