# Generated by Django 4.1.3 on 2023-01-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_transaction_wallet'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
