# Generated by Django 4.1.3 on 2023-01-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_transaction_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
    ]
