# Generated by Django 4.1.7 on 2023-04-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_audio_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
