# Generated by Django 4.1.7 on 2023-05-07 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0029_validation_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTranscriptionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('audios', models.ManyToManyField(db_index=True, related_name='transcriptions_assignments', to='dashboard.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aligned_transcription_audios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
