# Generated by Django 4.1.3 on 2023-01-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_remove_transaction_wallet'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='payments.transaction'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
