# Generated by Django 4.1.3 on 2023-01-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_participant_transaction_delete_transaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audio',
            table='audios',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
        migrations.AlterModelTable(
            name='participant',
            table='participants',
        ),
        migrations.AlterModelTable(
            name='transcription',
            table='transcriptions',
        ),
        migrations.AlterModelTable(
            name='validation',
            table='validations',
        ),
    ]
