# Generated by Django 4.1.7 on 2023-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_audiotranscriptionassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='transcription_count',
            field=models.IntegerField(default=0),
        ),
    ]
