# Generated by Django 4.1.7 on 2023-05-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_image_transcription_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='transcription_count',
            new_name='transcription_count_ak_gh',
        ),
        migrations.AddField(
            model_name='image',
            name='transcription_count_dag_gh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='transcription_count_dga_gh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='transcription_count_ee_gh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='transcription_count_kpo_gh',
            field=models.IntegerField(default=0),
        ),
    ]
