# Generated by Django 4.1.3 on 2023-01-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_audio_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
