# Generated by Django 4.1.3 on 2023-01-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_rename_directions_transaction_direction'),
        ('dashboard', '0032_alter_notification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='payments.transaction'),
        ),
    ]
