# Generated by Django 4.1.7 on 2023-05-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('dashboard', '0033_participant_balance_participant_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='participants', to='payments.transaction'),
        ),
    ]
