# Generated by Django 4.1.3 on 2023-01-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_participant_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='is_accepted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='audio',
            name='validation_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='batch_number',
            field=models.IntegerField(blank=True, db_index=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_accepted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='momo_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='is_accepted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='validation_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
