# Generated by Django 4.1.7 on 2023-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_exporttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
