# Generated by Django 4.1.7 on 2023-06-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_validation_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='second_audio_status',
            field=models.TextField(choices=[('in_review', 'in_review'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], db_index=True, default='pending'),
        ),
    ]
