# Generated by Django 4.1.7 on 2023-07-07 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0038_alter_audiotranscriptionassignment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionResolutionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('audios', models.ManyToManyField(db_index=True, related_name='transcription_resolutions_assignments', to='dashboard.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinged_transcription_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
