# Generated by Django 4.1.7 on 2023-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email_address',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
