# Generated by Django 4.1.7 on 2023-10-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_participant_excluded_from_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
